## RabbitMQ Configuration
## See https://www.rabbitmq.com/configure.html for further config options

# ============================================
# Core
# ============================================
listeners.tcp.default = 5672

# ============================================
# Management Plugin
# ============================================
management.listener.port = 15672
# management.load_definitions = /etc/rabbitmq/definitions.json  # uncomment and mount file to pre-seed queues/exchanges

# ============================================
# Clustering
# ============================================
cluster_partition_handling = autoheal

# ============================================
# Memory and Limits
# ============================================
vm_memory_high_watermark.relative = 0.6
channel_max = 2048

