version = 0.1

[default.deploy.parameters]
stack_name = "smart-hiring-phase1-deploy"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = false
resolve_s3 = true
s3_prefix = "smart-hiring-phase1-deploy"
template_file = "serverless/phase1/template.yaml"

