apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-hiring
resources:
  - namespace.yaml
  - api-gateway.yaml
  - resume-parser-service.yaml
  - screening-bot-service.yaml
  - candidate-matcher-service.yaml
  - interview-prep-service.yaml
  - notification-service.yaml
  - servicemonitors.yaml

