apiVersion: v1
kind: Secret
metadata:
  name: smart-hiring-secrets
  namespace: smart-hiring
type: Opaque
stringData:
  postgres-password: "replace-me"
  rabbitmq-password: "replace-me"
  redis-password: "replace-me"
  mongodb-uri: "mongodb://hiring_user:replace-me@mongodb:27017/smart_hiring_db?authSource=admin"
  openai-api-key: "replace-me"
  mail-username: "replace-me"
  mail-password: "replace-me"
  twilio-account-sid: "replace-me"
  twilio-auth-token: "replace-me"
  twilio-from-number: "replace-me"

