spring:
  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

notification:
  email:
    enabled: true

management:
  health:
    mail:
      enabled: false

